### ISSUE TITLE
google pixel 7 pro can't install APK

### ISSUE THREAD

**Issue by sniperleon** [AM2R-Community-Developers/AM2R-Community-Updates#124]
**Describe the bug**
My google pixel 7 pro can't install game.

**To Reproduce**
Use AM2RLauncher.exe to build AM2R.apk, installing to pixel 7 pro show error info "can't install this app to device"

**Expected behavior**
I'm thinking pixel 7 pro only support for 64bit.
So APK is build 32bit, can rebuild to 64bit?

**Media**
![562912](https://user-images.githubusercontent.com/29691706/224495199-4ed69c9e-697e-4719-a66a-9d2f48967410.jpg)

**Platform (please complete the following information):**
 - OS: Android
 - Version: 13

**Game Version:**
v2.3.0

**Comment by Miepee** [comment]
You're correct. This issue stems from the pixel pro 7 not allowing installing 32-bit applications. This will soon roll out to more and more devices and is AFAIK planned to be system wide with Android 14.

Sadly, we are unable to compile a 64bit version. The game was made with GameMaker Studio 1.4 (as you may be able to see in the readme of this repo), and thus only allows 32-bit compilation (for windows, linux and android).

We want to provide 64-bits builds too, so that newer OS are able to play it as well, but unfortunately we are currently unable to do this.
The only workarounds you can do yourself for the moment is doing any of these:
- Getting an older phone
- Downgrading to an earlier android version
- Emulating a 32bit system.

None of those options are pleasant to do :/
