### ISSUE TITLE
Cause repalette shaders to /not/ run by default

### ISSUE THREAD

**Issue by Lojemiru** [AM2R-Community-Developers/AM2R-Community-Updates#77]
**Is your feature request related to a problem? Please describe.**
The repalette shader cause odd behavior and/or slowdowns on certain systems.

**Describe the solution you'd like**
Since the shader functionality is only used by a small fraction of players, it would make sense to either move the palettes into an "inactive" folder or to add an in-game toggle to enable them via the Extras menu to prevent issues for the average user.

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.reddit.com/r/AM2R/comments/mbgkuk/i_have_found_a_glitch/

**Comment by Miepee** [comment]
> to prevent issues for the average user.
The average user wouldn't even encounter odd behaviour nor slowdowns (unless we're talking about android version). This would only happen on very out-of-date graphics drivers and/or old OS. 
I even tested AM2R on an old pentium P8600 laptop, no strange behaviour regarding the palette shader noticed there.
I'm all for the idea to introduce some kind of in-game toggle, but I'd rather make it default to true, instead of false.
